# Generated by Django 4.1.1 on 2022-09-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonCardinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_card', models.IntegerField()),
                ('y_card', models.IntegerField()),
                ('z_card', models.IntegerField()),
                ('timestamps', models.IntegerField()),
            ],
        ),
    ]
